---
name: "Code Quality: Packer"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  packer:
    name: Packer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./packer"
    env:
      PKR_VAR_subscription_id: ${{ secrets.PKR_VAR_SUBSCRIPTION_ID }}
      PKR_VAR_client_id: ${{ secrets.PKR_VAR_CLIENT_ID }}
      PKR_VAR_client_secret: ${{ secrets.PKR_VAR_CLIENT_SECRET }}
      PKR_VAR_tenant_id: ${{ secrets.PKR_VAR_TENANT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Format Packer files
        uses: operatehappy/packer-github-actions@v0.3.0
        with:
          command: fmt
          target: .      
          
      - name: Validate Packer files
        uses: operatehappy/packer-github-actions@v0.3.0
        with:
          command: validate
          arguments: -syntax-only
          target: .